<?php

namespace App\Validator;

use DateTimeInterface;
use Symfony\Component\Validator\Constraint;

/**
 * @Annotation
 */
class Time extends Constraint
{
    /*
     * Any public properties become valid options for the annotation.
     * Then, use these in your validator class.
     */
    public $message35 = 'Le temps choisie dépasse les 35h.';
    public $message0 = 'Le temps choisie ne peut pas être 0h.';
    // in the base Symfony\Component\Validator\Constraint class
    public function getTargets()
    {
        return self::CLASS_CONSTRAINT; // TODO: Change the autogenerated stub
    }

    public function validatedBy()
    {
       return static::class.'Validator'; // TODO: Change the autogenerated stub
    }
}
